In [1]:
from ctpn.ctpn import CTPN_model
from setting import ckpt_path
print(ckpt_path)
ctpn_model = CTPN_model(ckpt_path)

./ctpn/ckpt


Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)



Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell))`, which is equivalent to this API
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Instructions for updating:
Please use `layer.add_weight` method instead

In [2]:
from PIL import Image
import cv2
import time
from IPython.display import display


img = cv2.imread('test/61ys.jpg',1)
start = time.time()

text_recs = ctpn_model.predict(img)
print(time.time()-start)

7.174528121948242


In [3]:
import numpy as np
from pytesseract import image_to_string
import os
from ocr.ocr import CrnnOcr

crnn = CrnnOcr('ocr/model/model_acc97.pth')

xDim, yDim = img.shape[1], img.shape[0]
for index, rec in enumerate(text_recs):
    start = time.time()
    pt1 = [max(1, rec[0]), max(1, rec[1])]
    pt3 = [min(rec[6], xDim - 2), min(yDim - 2, rec[7])]
    partImg = img[pt1[1]:pt3[1], pt1[0]:pt3[0]]
    display(Image.fromarray(partImg))
    image = Image.fromarray(partImg).convert('L')
    print(crnn.predict(image))
    print(time.time()-start)

tensor([[[ -69.2633,  -71.0773, -112.2384,  ..., -131.9213, -106.1546,
          -109.6250]],

        [[  11.3750,  -21.0640,  -50.8037,  ...,  -50.7030,  -83.7179,
           -83.7922]],

        [[   6.5937,  -31.1542,  -65.2691,  ...,  -84.9830,  -78.7541,
           -91.2329]],

        ...,

        [[   2.7887,  -21.0078,  -60.4625,  ...,  -74.2270,  -66.5632,
           -66.8428]],

        [[  18.6197,  -12.2684,  -50.6524,  ...,  -65.2416,  -66.5809,
           -54.5033]],

        [[   5.3533,   -2.4125,  -30.2382,  ...,  -48.7492,  -52.6363,
           -34.9340]]], grad_fn=<ViewBackward>)
\机动车驾驶培训教练员从业资格考试申请表-样表-
\机动车驾驶培训教练员从业资格考试申请表-样表-
0.33190393447875977


tensor([[[ -61.8095,  -68.0268,  -96.5650,  ..., -130.8629, -102.0102,
          -109.1437]],

        [[  24.7002,   -2.5402,  -29.5345,  ...,  -41.0985,  -69.3867,
           -70.3674]],

        [[   0.5925,  -34.5225,  -53.5422,  ...,  -74.7321,  -70.7381,
           -85.8887]],

        ...,

        [[  30.5140,   -0.9811,  -12.9399,  ...,  -31.1257,  -39.8120,
           -29.4934]],

        [[  40.0264,   14.7286,   -5.8050,  ...,  -16.6450,  -19.4502,
           -10.6771]],

        [[  13.6678,  -15.2305,  -39.6286,  ...,  -50.1121,  -53.1563,
           -41.2244]]], grad_fn=<ViewBackward>)
-张XX-|性别-男-学历-技术职称-
张XX-|性别-男-学历-技术职称-
0.2565793991088867


tensor([[[ -40.1480,  -37.9128,  -64.1023,  ...,  -48.9256,  -58.4048,
           -41.8906]],

        [[  10.9127,  -29.4118,  -67.3772,  ...,  -62.5743, -110.8935,
           -99.9679]],

        [[ -13.4175,  -48.5793,  -75.2382,  ...,  -70.5939, -100.2402,
           -95.8838]],

        ...,

        [[  17.9601,   10.8279,  -21.6165,  ...,   -0.3112,  -22.4916,
           -14.6649]],

        [[  66.9970,   28.3403,   -8.8313,  ...,    5.2679,  -23.8156,
           -15.3486]],

        [[  36.4134,    5.6653,  -20.9227,  ...,  -13.2175,  -27.6965,
           -21.5689]]], grad_fn=<ViewBackward>)
非名
非名
0.05748724937438965


tensor([[[ -73.1151,  -74.4001, -104.9721,  ..., -130.3830, -102.1001,
          -107.5868]],

        [[  37.3236,   11.7125,  -16.3649,  ...,  -28.0000,  -50.2355,
           -54.2185]],

        [[   0.4264,  -31.1312,  -47.7680,  ...,  -71.7549,  -64.0875,
           -79.6343]],

        ...,

        [[  33.3928,   -3.7225,  -28.3698,  ...,  -34.1203,   -9.0659,
           -42.4103]],

        [[  39.6383,   35.4074,   35.8920,  ...,   39.3431,   51.2205,
            10.6298]],

        [[  18.0132,  -12.4491,  -13.9209,  ...,    4.0911,   -1.3902,
           -24.7439]]], grad_fn=<ViewBackward>)
-大专
大专
0.04827070236206055


tensor([[[ -64.5854,  -68.4181,  -98.7722,  ..., -118.5909,  -94.3186,
          -100.9887]],

        [[  21.3152,   -6.9974,  -43.9389,  ...,  -56.0624,  -79.7207,
           -83.0557]],

        [[  -2.4686,  -40.7380,  -67.4380,  ...,  -88.8720,  -79.0485,
           -96.8639]],

        ...,

        [[  17.7195,  -28.1321, -104.6240,  ..., -116.1252, -115.6993,
           -77.4587]],

        [[  13.7505,  -33.2736, -116.8434,  ..., -109.2354, -110.8749,
           -69.3893]],

        [[ -23.6500,  -31.6017,  -78.2198,  ...,  -69.6730,  -75.1721,
           -41.9945]]], grad_fn=<ViewBackward>)
-照
照
0.05665087699890137


tensor([[[ -71.1596,  -79.1629, -107.3920,  ..., -124.8440, -104.2792,
          -102.9046]],

        [[   0.9963,  -27.6685,  -51.9909,  ...,  -61.2102,  -81.8808,
           -83.7017]],

        [[   1.9853,  -35.2699,  -59.2013,  ...,  -78.1944,  -73.5183,
           -84.9312]],

        ...,

        [[   6.1969,  -23.1241,  -49.9107,  ...,  -73.6919,  -45.5235,
           -40.8395]],

        [[  -3.9776,  -25.5102,  -63.5854,  ...,  -82.5202,  -71.2009,
           -64.3171]],

        [[   2.8187,  -21.1709,  -49.8979,  ...,  -67.5279,  -49.5883,
           -43.1040]]], grad_fn=<ViewBackward>)
-住址XX市XX区XX路XX弄XX号XX室-电话-58xxxxxx
住址XX市XX区XX路XX弄XX号XX室-电话-58xxxxxx
0.3657400608062744


tensor([[[-121.7054, -122.5801, -159.5970,  ..., -152.1061, -167.1151,
          -138.5798]],

        [[ -11.5837,  -43.1620, -100.2343,  ...,  -95.6094, -138.5809,
          -111.7377]],

        [[ -19.1446,  -58.2065, -115.1630,  ..., -113.5905, -135.4629,
          -115.7139]],

        ...,

        [[ -20.0996,  -45.3503,  -71.5122,  ...,  -90.4594,  -72.0778,
           -73.9070]],

        [[  26.9917,   -8.4787,  -20.9088,  ...,  -42.4131,  -23.9312,
           -32.7555]],

        [[ -27.5429,  -55.5500,  -65.9625,  ...,  -86.0266,  -75.9954,
           -78.9572]]], grad_fn=<ViewBackward>)
工作单位，XXXXXXXXXX公司
工作单位，XXXXXXXXXX公司
0.18636608123779297


tensor([[[ -89.7585,  -84.8784, -127.6335,  ..., -120.5350, -130.9301,
          -116.7460]],

        [[  14.8940,  -22.9440,  -62.2534,  ...,  -54.7265, -101.8540,
           -93.8587]],

        [[  -4.3542,  -40.0364,  -78.4153,  ...,  -82.8371,  -95.3086,
           -92.4941]],

        ...,

        [[   0.5561,  -20.5293,  -50.7166,  ...,  -71.4536,  -59.1601,
           -54.3286]],

        [[  15.6561,   -8.1351,  -32.5978,  ...,  -57.4951,  -37.1891,
           -37.1035]],

        [[ -10.3591,  -35.0890,  -61.5411,  ...,  -88.6492,  -70.1302,
           -56.8921]]], grad_fn=<ViewBackward>)
-电话-65XxxXxx
电话-65XxxXxx
0.14228081703186035


tensor([[[-21.2604, -18.0791, -23.0879,  ..., -28.3223, -25.6192, -38.9790]],

        [[ 33.1914,  -4.2000, -31.2097,  ..., -36.5277, -75.6672, -88.8148]],

        [[ 18.0319, -19.0956, -44.9159,  ..., -57.5731, -72.4266, -84.8302]],

        ...,

        [[ 23.0750, -10.2532, -28.5699,  ..., -22.2912, -19.2895, -33.6537]],

        [[ 32.1947,   5.1451, -21.0652,  ..., -36.2353, -27.2115, -28.8907]],

        [[  7.9576, -23.5408, -43.8588,  ..., -66.1267, -54.8295, -48.6025]]],
       grad_fn=<ViewBackward>)
匀份证号
匀份证号
0.07731223106384277


tensor([[[-52.9373, -57.8304, -87.7600,  ..., -93.7316, -79.1738, -86.1057]],

        [[ 10.3819, -17.5130, -31.6896,  ..., -39.5403, -61.0126, -73.7074]],

        [[  2.5400, -35.1753, -41.5865,  ..., -63.0291, -56.1576, -79.9702]],

        ...,

        [[  5.1134,  -4.1086,  -6.0070,  ...,   4.9372, -33.2122,  -0.6443]],

        [[ 29.9589, -10.3317, -20.0603,  ...,  -7.0166, -44.7018, -17.9707]],

        [[ -8.3569, -41.2582, -51.1161,  ..., -46.7538, -70.6039, -56.4681]]],
       grad_fn=<ViewBackward>)
培训单位
培训单位
0.07740473747253418


tensor([[[ -60.7565,  -63.4075, -102.6716,  ..., -108.8096, -101.5503,
           -91.8897]],

        [[  12.7041,  -11.8607,  -49.5755,  ...,  -63.4930,  -76.6665,
           -82.8174]],

        [[   4.6609,  -30.0635,  -54.9595,  ...,  -72.5272,  -59.8092,
           -77.5615]],

        ...,

        [[  26.5709,   -8.8635,  -39.1157,  ...,  -46.5343,  -34.6891,
           -21.3727]],

        [[  21.9171,   -2.7335,  -44.6814,  ...,  -53.7278,  -49.3603,
           -25.0671]],

        [[ -12.3963,  -24.7804,  -61.7025,  ...,  -70.4663,  -61.1247,
           -40.9767]]], grad_fn=<ViewBackward>)
-310223XXXXXXXXXXXX
310223XXXXXXXXXXXX
0.1678636074066162


tensor([[[-25.1445, -23.1872, -55.8257,  ..., -66.0550, -43.7275, -44.5604]],

        [[ 35.5122,   3.0735, -49.8997,  ..., -47.8547, -81.0347, -76.8181]],

        [[ 10.1607, -30.0339, -64.3705,  ..., -78.3026, -76.9470, -85.9234]],

        ...,

        [[-20.2040, -48.0519, -75.6027,  ..., -92.1626, -81.1904, -77.7002]],

        [[ 27.8277,  -5.7173, -27.4319,  ..., -49.3701, -37.1801, -38.3150]],

        [[-41.3845, -62.5980, -77.7776,  ..., -99.1861, -85.4775, -87.3890]]],
       grad_fn=<ViewBackward>)
XXXXXXXXXX公司
XXXXXXXXXX公司
0.14157557487487793


tensor([[[ -77.4637,  -73.0767, -103.2877,  ...,  -90.4413,  -91.6627,
           -85.5194]],

        [[  -1.0112,  -37.3467,  -87.8698,  ...,  -70.6281, -112.9682,
          -108.7464]],

        [[  13.8431,  -26.3718,  -63.7975,  ...,  -61.7214,  -68.0512,
           -73.3189]],

        ...,

        [[  16.7983,   -8.1821,  -44.5281,  ...,  -45.9421,  -61.5098,
           -32.2253]],

        [[  49.8579,   27.5624,    1.3819,  ...,   -1.4084,    2.8684,
             8.3140]],

        [[   9.7134,  -16.8155,  -44.0636,  ...,  -62.0177,  -52.3870,
           -41.4079]]], grad_fn=<ViewBackward>)
-驶证准
驶证准
0.07891011238098145


tensor([[[ -90.1496,  -96.2602, -128.9850,  ..., -155.5232, -129.3645,
          -134.5520]],

        [[  16.1964,  -17.4887,  -51.2713,  ...,  -60.1884,  -82.3211,
           -88.9285]],

        [[  -8.6708,  -47.1483,  -78.0095,  ..., -100.7576,  -99.2538,
          -113.7607]],

        ...,

        [[   0.2288,  -35.9141,  -76.8276,  ...,  -61.1325,  -96.9333,
           -59.8224]],

        [[  26.7668,  -14.3874,  -45.4103,  ...,  -20.8146,  -64.4769,
           -24.3649]],

        [[   3.5210,    0.9699,   -5.8969,  ...,   27.8849,  -14.6206,
             6.0783]]], grad_fn=<ViewBackward>)
-20XX年X月X日
20XX年X月X日
0.1372818946838379


tensor([[[ -76.9099,  -81.0547, -110.9192,  ..., -131.6485, -109.1360,
          -110.7047]],

        [[  19.8987,   -9.3062,  -42.3738,  ...,  -53.9064,  -80.6031,
           -79.4587]],

        [[  -9.6706,  -47.0298,  -72.2805,  ...,  -95.8127,  -86.8407,
          -101.9654]],

        ...,

        [[  26.4922,  -12.4595,  -33.7081,  ...,  -45.1596,  -42.2688,
           -39.8172]],

        [[  39.2477,   17.7269,  -15.2854,  ...,  -29.6949,  -28.3474,
           -25.7477]],

        [[   6.2777,  -16.6774,  -40.0027,  ...,  -57.8016,  -54.2945,
           -45.0323]]], grad_fn=<ViewBackward>)
-初领驾驶证日期
初领驾驶证日期
0.17031407356262207


tensor([[[-7.6619e+01, -7.9133e+01, -1.0859e+02,  ..., -1.3950e+02,
          -1.2555e+02, -1.1824e+02]],

        [[ 2.1880e+01, -1.0105e-01, -1.4322e+01,  ..., -3.1058e+01,
          -5.4028e+01, -6.1852e+01]],

        [[ 1.4336e+00, -2.8979e+01, -4.1946e+01,  ..., -6.8995e+01,
          -6.2505e+01, -8.1103e+01]],

        ...,

        [[-2.4895e+01, -3.7067e+01, -5.4362e+01,  ..., -9.4678e+01,
          -8.6181e+01, -6.7286e+01]],

        [[ 2.2313e+01,  1.1860e+00, -2.2747e+01,  ..., -5.1020e+01,
          -4.4950e+01, -2.4877e+01]],

        [[-4.7793e-01, -3.2194e+01, -5.8352e+01,  ..., -8.5650e+01,
          -7.2369e+01, -5.6069e+01]]], grad_fn=<ViewBackward>)
.A1
.A1
0.048375844955444336


tensor([[[ -76.0732,  -79.9663, -112.0186,  ..., -132.9444, -111.2103,
          -111.9412]],

        [[  32.0340,    3.4034,  -30.3496,  ...,  -42.2883,  -69.5675,
           -70.8195]],

        [[  -0.5366,  -35.5583,  -55.5072,  ...,  -78.9025,  -74.0297,
           -87.8282]],

        ...,

        [[  24.3882,   10.3506,  -26.0600,  ...,  -17.7528,   -8.1744,
            11.2535]],

        [[  36.6419,   -1.2556,  -39.0811,  ...,  -25.6856,  -28.5032,
            -9.3193]],

        [[   3.3785,  -32.4835,  -65.0083,  ...,  -47.9312,  -65.9638,
           -50.8645]]], grad_fn=<ViewBackward>)
-驾车型
驾车型
0.1307544708251953


tensor([[[ -45.0354,  -43.3646,  -58.5033,  ...,  -40.0256,  -61.4168,
           -59.4083]],

        [[   3.6610,  -25.7425,  -63.7981,  ...,  -43.2539,  -99.0478,
           -90.9863]],

        [[   2.2582,  -26.8945,  -60.3618,  ...,  -51.6197,  -83.9596,
           -87.2620]],

        ...,

        [[ -39.3489,  -77.2529, -115.8483,  ..., -105.8923, -137.6494,
          -103.1623]],

        [[  -9.8274,  -49.8634,  -78.1412,  ...,  -58.3316,  -93.9189,
           -59.9881]],

        [[ -36.4360,  -41.7053,  -50.3418,  ...,  -20.5900,  -61.7144,
           -41.3780]]], grad_fn=<ViewBackward>)
伊然。-，理论赞练员口驾驶探作数练员口
伊然。-，理论赞练员口驾驶探作数练员口
0.2045300006866455


tensor([[[ -64.0045,  -64.4281, -104.0119,  ..., -105.3092, -108.4441,
          -103.0466]],

        [[  21.1182,  -17.4427,  -69.8793,  ...,  -57.1962, -108.6965,
          -102.8090]],

        [[  13.4254,  -37.2297,  -63.5446,  ...,  -74.4382,  -93.9538,
           -83.7036]],

        ...,

        [[   8.0574,  -23.6048,  -57.6414,  ...,  -59.8451,  -63.2286,
           -67.6512]],

        [[  25.7164,   -0.8198,  -21.3615,  ...,  -36.8155,  -23.3716,
           -17.0441]],

        [[   4.6534,   -5.1387,  -11.4511,  ...,  -35.9794,  -24.1997,
           -13.5909]]], grad_fn=<ViewBackward>)
-根据实际申请内容进行勾选，
根据实际申请内容进行勾选，
0.15409588813781738


tensor([[[ -62.8987,  -68.1126, -109.9453,  ..., -140.8965, -101.9897,
          -117.2581]],

        [[  17.7394,   -8.8862,  -32.1123,  ...,  -43.4413,  -56.5491,
           -74.9457]],

        [[   5.4838,  -34.5486,  -48.3717,  ...,  -72.3562,  -64.8083,
           -87.1017]],

        ...,

        [[ -12.0028,  -32.1020,  -53.8917,  ...,  -73.7847,  -58.4348,
           -60.0442]],

        [[  30.6245,    0.3222,  -12.7796,  ...,  -40.2679,  -21.7078,
           -28.7825]],

        [[ -23.3550,  -48.4289,  -59.5909,  ...,  -80.8414,  -69.4283,
           -71.7262]]], grad_fn=<ViewBackward>)
类别
类别
0.06385397911071777


tensor([[[ -31.8278,  -51.8023,  -60.4129,  ...,  -57.9932,  -63.1056,
           -68.8816]],

        [[  13.8004,  -21.2581,  -57.3728,  ...,  -55.8106,  -97.7302,
          -101.5832]],

        [[  10.2460,  -32.9559,  -71.7873,  ...,  -86.9849,  -91.5119,
           -93.9536]],

        ...,

        [[ -26.2478,  -63.6083,  -96.2881,  ..., -115.5142, -113.4556,
           -97.7379]],

        [[ -10.1473,  -58.1239,  -81.8382,  ...,  -96.9582,  -99.3966,
           -80.1715]],

        [[ -46.1379,  -56.5932,  -75.1238,  ...,  -77.6597,  -85.4951,
           -77.5079]]], grad_fn=<ViewBackward>)
申申诸准敬A1-A2-A3-B1-B2-C1-C2-C3-c4-C5-D-E-F
申申诸准敬A1-A2-A3-B1-B2-C1-C2-C3-c4-C5-D-E-F
0.5029807090759277


tensor([[[ -86.1253,  -92.0221, -114.9347,  ..., -132.9219, -114.3367,
          -124.4259]],

        [[  10.0067,  -17.4587,  -45.8797,  ...,  -58.2619,  -80.1248,
           -87.5276]],

        [[ -14.1241,  -50.3190,  -77.2179,  ..., -100.5716,  -97.2545,
          -115.5201]],

        ...,

        [[   0.7875,  -24.8069,  -62.7245,  ...,  -83.2895,  -78.4409,
           -82.1518]],

        [[  -8.8775,  -40.0129,  -64.4630,  ...,  -98.7041,  -81.4919,
           -79.0061]],

        [[  -1.4481,   -1.9863,  -22.6000,  ...,  -50.2037,  -39.2415,
           -32.5863]]], grad_fn=<ViewBackward>)
-车型--M--N-P-口-根据实际申请内容进行勾选》
车型--M--N-P-口-根据实际申请内容进行勾选》
0.337813138961792


tensor([[[ -69.6061,  -67.8833, -101.9292,  ..., -116.5270,  -99.8385,
          -100.8232]],

        [[  32.3817,    9.6784,  -11.7554,  ...,  -25.4785,  -46.8866,
           -56.1823]],

        [[   1.7279,  -34.5909,  -46.1219,  ...,  -70.7423,  -60.4053,
           -83.5158]],

        ...,

        [[ -41.5474,  -91.4322, -137.4880,  ..., -120.2156, -150.6534,
          -101.4536]],

        [[ -17.3920,  -65.8965,  -87.8554,  ...,  -63.2353,  -99.6162,
           -58.0840]],

        [[ -37.3311,  -50.2500,  -66.6004,  ...,  -40.8895,  -79.4474,
           -44.0321]]], grad_fn=<ViewBackward>)
-身份证明复印件-学历证明原件口
身份证明复印件-学历证明原件口
0.20937538146972656


tensor([[[-105.7806, -111.5685, -121.0626,  ..., -143.0635, -142.4639,
          -142.2522]],

        [[  19.1831,  -11.7738,  -41.4605,  ...,  -56.2592,  -86.5968,
           -92.7906]],

        [[   5.6510,  -29.5243,  -48.4572,  ...,  -73.9681,  -87.5379,
           -91.8071]],

        ...,

        [[  35.0755,    9.5657,  -21.4467,  ...,   -1.5564,  -21.1815,
            -3.0618]],

        [[  19.7832,   -2.2741,  -38.9963,  ...,  -41.3128,  -41.5375,
           -36.7253]],

        [[   9.1178,  -19.2642,  -46.2387,  ...,  -61.0923,  -52.2554,
           -49.4481]]], grad_fn=<ViewBackward>)
-身份证明原件-
身份证明原件-
0.1257340908050537


tensor([[[ -63.6303,  -57.3998,  -91.0677,  ...,  -83.6934, -112.3989,
           -76.5158]],

        [[  26.5183,    3.0313,  -26.8553,  ...,  -24.4819,  -83.0320,
           -56.6750]],

        [[  -6.8205,  -36.7645,  -68.1320,  ...,  -78.8836, -100.7812,
           -86.6485]],

        ...,

        [[   3.0294,  -16.4146,  -48.3348,  ...,  -73.9016,  -63.6177,
           -60.2422]],

        [[  42.3731,   17.9203,   -7.5396,  ...,  -36.5278,  -19.5483,
           -15.6109]],

        [[ -29.2028,  -54.3529,  -77.8935,  ..., -100.0968,  -88.7448,
           -84.4657]]], grad_fn=<ViewBackward>)
-、---学历证明爱印件-技术职称证明原件-技术职称证明复印件-
、---学历证明爱印件-技术职称证明原件-技术职称证明复印件-
0.5090370178222656


tensor([[[ -68.4014,  -76.5131, -113.2069,  ..., -129.0278, -108.4414,
          -114.8033]],

        [[  14.6383,  -20.1167,  -67.9025,  ...,  -74.9582, -103.3783,
          -102.3810]],

        [[ -10.7305,  -48.5871,  -76.9473,  ...,  -98.2930,  -97.1184,
          -109.9480]],

        ...,

        [[  -6.7196,  -32.3355,  -69.8669,  ...,  -91.8905,  -83.8775,
           -74.6520]],

        [[  36.9228,    8.9911,  -12.5884,  ...,  -38.5443,  -20.4332,
           -17.0856]],

        [[ -22.3058,  -50.7997,  -69.3294,  ...,  -94.1262,  -84.1272,
           -77.0505]]], grad_fn=<ViewBackward>)
-安全驾驶经历证明口
安全驾驶经历证明口
0.21105480194091797


tensor([[[-109.3069, -120.8011, -127.3815,  ..., -149.2737, -150.8212,
          -148.4478]],

        [[   3.4833,  -31.7517,  -61.8285,  ...,  -82.1293, -118.0937,
          -117.7253]],

        [[   1.3631,  -34.5604,  -55.0056,  ...,  -84.1059, -105.7971,
          -101.3112]],

        ...,

        [[  17.9820,   -1.5748,  -36.6866,  ...,  -27.3676,  -36.1071,
           -17.4678]],

        [[  24.9085,    3.9265,  -30.2138,  ...,  -41.7200,  -33.5747,
           -32.6137]],

        [[  -9.0520,  -37.6695,  -59.7905,  ...,  -82.0659,  -74.3012,
           -65.2364]]], grad_fn=<ViewBackward>)
-驾驶证原件-
驾驶证原件-
0.20041465759277344


tensor([[[ -81.9991,  -86.0644, -108.6061,  ..., -128.5302, -103.2839,
          -118.5359]],

        [[  19.3453,   -5.0575,  -29.2611,  ...,  -43.8228,  -62.4020,
           -73.0277]],

        [[  -9.5227,  -43.4954,  -64.2896,  ...,  -85.2624,  -81.4406,
           -98.4328]],

        ...,

        [[   2.9965,  -18.1470,  -51.9313,  ...,  -75.5941,  -60.4289,
           -54.9230]],

        [[  47.6061,   20.4185,    1.3751,  ...,  -23.6750,   -5.2226,
            -3.3699]],

        [[ -17.8558,  -48.4319,  -67.6694,  ...,  -89.4222,  -82.6870,
           -73.4712]]], grad_fn=<ViewBackward>)
-驾驶证复印件-
驾驶证复印件-
0.11775612831115723


tensor([[[-107.0199, -110.8915, -127.0860,  ..., -161.4115, -153.5895,
          -148.4650]],

        [[   6.6945,  -27.7254,  -59.0702,  ...,  -86.4263, -105.5177,
          -112.0239]],

        [[  15.8348,  -26.5339,  -52.4065,  ...,  -92.6030,  -94.7278,
           -98.9920]],

        ...,

        [[ -18.6669,  -53.0931, -109.4662,  ...,  -90.6303, -118.2275,
           -75.3658]],

        [[   1.4431,  -33.8084,  -86.1920,  ...,  -52.1576,  -87.9850,
           -33.6437]],

        [[ -31.4975,  -31.5264,  -67.1400,  ...,  -35.7845,  -68.1181,
           -26.6099]]], grad_fn=<ViewBackward>)
，相应车型驾驶经历证明-原从业资格证炙印件--相应教学经历证明-
，相应车型驾驶经历证明-原从业资格证炙印件--相应教学经历证明-
0.984107255935669


tensor([[[ -68.5230,  -75.4997, -107.1512,  ..., -115.9369, -100.9343,
          -103.6311]],

        [[  22.7873,  -11.8922,  -48.0677,  ...,  -53.3711,  -77.4891,
           -79.3157]],

        [[ -10.6880,  -47.6369,  -70.4239,  ...,  -95.1566,  -87.5860,
          -103.1957]],

        ...,

        [[  -2.9159,  -21.9127,  -41.6254,  ...,  -46.0976,  -39.6655,
           -31.1851]],

        [[   4.2919,  -20.8660,  -50.4327,  ...,  -58.0022,  -50.1842,
           -49.2652]],

        [[   2.1671,  -31.9716,  -57.1281,  ...,  -67.6670,  -61.6131,
           -55.9262]]], grad_fn=<ViewBackward>)
-本人承诺上述所有内容真实、有效，并承担由此产生的法律责任。
本人承诺上述所有内容真实、有效，并承担由此产生的法律责任。
0.3416292667388916


tensor([[[-57.4734, -54.5440, -70.5874,  ..., -76.4804, -74.5958, -66.7207]],

        [[ 30.5617,  -5.1380, -51.4055,  ..., -47.3750, -96.1121, -74.8757]],

        [[ 12.7038, -36.3504, -58.9944,  ..., -62.0582, -80.3329, -70.5705]],

        ...,

        [[ -6.5781, -29.6735, -43.5666,  ..., -51.1134, -46.0125, -30.6622]],

        [[ 21.5287,  -9.7423, -15.8670,  ..., -25.8084,  -8.4470,  -3.2811]],

        [[ 19.5485, -11.2337, -41.7790,  ..., -41.8782, -60.8366, -38.6464]]],
       grad_fn=<ViewBackward>)
《诺
《诺
0.08414864540100098


tensor([[[ -60.4896,  -57.6566,  -60.9749,  ...,  -75.3827,  -70.5224,
           -79.6531]],

        [[   7.1244,  -32.0758,  -72.2839,  ...,  -75.4687, -119.0017,
          -109.7456]],

        [[   0.9311,  -38.3435,  -75.0681,  ...,  -98.8617, -109.7776,
          -110.2975]],

        ...,

        [[   0.7029,  -27.1001,  -72.6311,  ...,  -85.8645,  -70.1050,
           -65.3459]],

        [[  43.3514,    9.2747,  -26.3491,  ...,  -53.8803,  -31.1064,
           -16.9072]],

        [[  -5.1923,  -17.1001,  -47.8880,  ...,  -71.5719,  -58.3524,
           -40.2118]]], grad_fn=<ViewBackward>)
本人签字:
本人签字:
0.05900382995605469


tensor([[[ -72.4544,  -79.8206, -115.7780,  ..., -136.1607, -115.4454,
          -127.4690]],

        [[  23.8935,  -11.4556,  -51.1681,  ...,  -62.6095,  -82.7915,
           -93.5207]],

        [[ -21.9037,  -57.2278,  -91.0798,  ..., -112.8935, -109.6786,
          -131.7470]],

        ...,

        [[   5.9375,  -11.4561,  -35.1532,  ...,  -60.7395,  -58.5160,
           -55.3172]],

        [[  27.5981,    7.8563,  -21.4847,  ...,  -42.5016,  -25.7002,
           -25.0671]],

        [[   6.3746,  -19.3586,  -47.2269,  ...,  -69.2886,  -56.4249,
           -43.7213]]], grad_fn=<ViewBackward>)
-张XX
张XX
0.06692171096801758


tensor([[[ -56.8789,  -66.5658,  -97.8465,  ..., -102.6065,  -86.9389,
           -86.1265]],

        [[  16.7451,  -12.8809,  -44.2103,  ...,  -51.5717,  -75.6800,
           -73.8645]],

        [[   5.7804,  -29.8417,  -49.8762,  ...,  -69.0717,  -63.8692,
           -74.0228]],

        ...,

        [[  -3.4169,  -32.5637,  -65.5298,  ...,  -76.7681,  -77.4237,
           -69.8345]],

        [[  35.0495,    6.8101,  -11.7004,  ...,  -28.4245,  -19.3858,
           -16.8230]],

        [[  -8.9272,  -42.4605,  -58.4336,  ...,  -81.5780,  -72.1722,
           -64.8272]]], grad_fn=<ViewBackward>)
日期20XX年XX月XX日
日期20XX年XX月XX日
0.1819617748260498


tensor([[[ -71.1918,  -71.5422, -108.5826,  ..., -120.6457, -114.4840,
           -99.2444]],

        [[  16.8317,   -6.5621,  -34.3887,  ...,  -50.5534,  -69.1039,
           -77.5425]],

        [[  -4.2633,  -41.5522,  -66.2877,  ...,  -86.0973,  -83.0148,
           -98.5930]],

        ...,

        [[  -4.8820,  -28.3883,  -57.3285,  ...,  -76.2131,  -65.9195,
           -56.0924]],

        [[  27.6034,    4.2061,  -19.9604,  ...,  -37.4779,  -27.0859,
           -20.6795]],

        [[ -15.2241,  -40.0348,  -62.5468,  ...,  -80.1571,  -71.1089,
           -53.9523]]], grad_fn=<ViewBackward>)
-监考人
监考人
0.17750930786132812


tensor([[[ -55.9828,  -58.9922,  -93.4290,  ..., -115.8689,  -92.5754,
           -96.7751]],

        [[  28.0943,   -4.6342,  -36.6762,  ...,  -50.4609,  -76.1208,
           -79.2803]],

        [[  -4.1832,  -43.8102,  -66.0601,  ...,  -90.9670,  -84.9408,
          -100.8593]],

        ...,

        [[ -14.1443,  -37.8020,  -63.6828,  ...,  -80.6128,  -65.3196,
           -65.5672]],

        [[  37.5912,    8.0709,   -8.4012,  ...,  -28.7731,  -12.0075,
           -17.3057]],

        [[ -27.9713,  -56.0624,  -74.8457,  ...,  -96.3182,  -81.3328,
           -81.0925]]], grad_fn=<ViewBackward>)
-科目
科目
0.07407212257385254


tensor([[[ -71.7208,  -75.9303,  -84.1127,  ...,  -92.2291,  -94.1977,
           -87.9409]],

        [[  18.9022,   -9.5473,  -39.7815,  ...,  -61.3081,  -83.9159,
           -82.2192]],

        [[  -6.3972,  -33.6297,  -44.1535,  ...,  -74.8827,  -73.7862,
           -79.3022]],

        ...,

        [[ -11.3164,  -33.9060,  -74.0833,  ..., -103.3494,  -74.9643,
           -70.1850]],

        [[  22.3356,   -9.8009,  -27.9551,  ...,  -54.7649,  -29.5323,
           -31.4386]],

        [[  -6.6283,  -21.6166,  -42.5922,  ...,  -66.0920,  -48.8736,
           -45.4468]]], grad_fn=<ViewBackward>)
《主考人
《主考人
0.09977269172668457


tensor([[[-61.9247, -67.6577, -83.1965,  ..., -85.7837, -88.9033, -82.7425]],

        [[ 15.5285, -17.2689, -54.6872,  ..., -65.8623, -92.9707, -89.1307]],

        [[ -5.5559, -38.5744, -52.5755,  ..., -74.2855, -76.0228, -80.4508]],

        ...,

        [[ -8.2119, -25.8973, -54.8553,  ..., -74.4770, -55.5458, -50.2366]],

        [[ 40.9541,  13.4812,  -3.4421,  ..., -23.2914,  -4.8319,  -5.4487]],

        [[ 12.0912,  -0.4715, -14.4347,  ..., -31.2528, -21.9525, -22.3042]]],
       grad_fn=<ViewBackward>)
《成“续
《成“续
0.05669808387756348


tensor([[[-6.0513e+01, -7.0131e+01, -9.8266e+01,  ..., -1.1411e+02,
          -9.8728e+01, -9.7567e+01]],

        [[ 3.0356e+01, -5.5397e-02, -2.4428e+01,  ..., -4.0498e+01,
          -5.7786e+01, -6.3862e+01]],

        [[-1.7682e+00, -3.4871e+01, -5.3475e+01,  ..., -8.1428e+01,
          -7.3664e+01, -8.4934e+01]],

        ...,

        [[-1.5195e+01, -3.7655e+01, -6.0464e+01,  ..., -8.8969e+01,
          -6.8784e+01, -6.8400e+01]],

        [[ 1.7788e+01, -1.5635e+01, -2.6627e+01,  ..., -5.5604e+01,
          -3.9484e+01, -3.7793e+01]],

        [[-3.2751e+01, -4.9716e+01, -6.3101e+01,  ..., -8.3336e+01,
          -7.4276e+01, -7.0498e+01]]], grad_fn=<ViewBackward>)
-日期
日期
0.07984590530395508


tensor([[[-105.8876,  -97.8484, -145.2606,  ..., -143.8408, -147.4784,
          -133.8220]],

        [[  11.1514,  -24.8693,  -55.9846,  ...,  -47.4477,  -99.8020,
           -90.2472]],

        [[  -9.7807,  -46.6612,  -82.4932,  ...,  -81.0524,  -92.8186,
           -92.8594]],

        ...,

        [[  -2.4945,  -33.5546,  -65.7088,  ...,  -92.2983,  -96.2313,
           -86.9098]],

        [[ -10.2904,  -38.0541,  -49.4812,  ...,  -70.1443,  -82.0357,
           -62.7714]],

        [[ -26.3539,  -25.2489,  -39.1486,  ...,  -65.0048,  -66.1216,
           -45.0217]]], grad_fn=<ViewBackward>)
-申请人无需--申请人无需|-申请人无需--申请人无/
申请人无需--申请人无需|-申请人无需--申请人无/
0.3177978992462158


tensor([[[ -63.2715,  -53.0131,  -55.8995,  ...,  -59.3232,  -58.0430,
           -67.2513]],

        [[  21.3945,   -8.6693,  -41.1045,  ...,  -45.0201,  -89.2225,
           -77.7790]],

        [[   3.0781,  -26.9652,  -59.0760,  ...,  -72.6993,  -83.2814,
           -87.5133]],

        ...,

        [[   5.9664,  -14.9360,  -40.8423,  ...,  -66.1894,  -55.3594,
           -45.0142]],

        [[  -8.5026,  -41.2056,  -61.4342,  ..., -100.4131,  -70.0923,
           -57.5314]],

        [[   0.8793,   -8.2764,  -10.0782,  ...,  -39.1139,  -13.6336,
            -7.0985]]], grad_fn=<ViewBackward>)
秀这-理论知识考试，雪”
秀这-理论知识考试，雪”
0.176133394241333


tensor([[[ -46.0642,  -43.4823,  -70.8406,  ...,  -74.9917,  -56.6290,
           -73.1044]],

        [[   5.0270,  -32.8834,  -75.3260,  ...,  -78.0014, -106.7759,
          -116.9494]],

        [[   7.5131,  -31.2263,  -76.5062,  ...,  -86.4927,  -99.6810,
          -110.6903]],

        ...,

        [[   4.3687,  -31.6309,  -72.5660,  ...,  -96.7708,  -82.4992,
           -72.8528]],

        [[  51.3992,   21.6654,    1.6183,  ...,  -21.7408,   -9.3433,
            -2.9246]],

        [[  16.6293,   14.9881,  -12.9034,  ...,  -37.4851,  -29.2351,
           -19.2624]]], grad_fn=<ViewBackward>)
填写-
填写-
0.08291316032409668


tensor([[[ -58.3399,  -55.0107,  -85.1023,  ..., -100.6347,  -79.7874,
           -87.5799]],

        [[  12.8445,  -11.8183,  -32.7956,  ...,  -40.0562,  -60.0184,
           -74.6208]],

        [[   5.0144,  -31.1218,  -46.3174,  ...,  -65.6627,  -63.1651,
           -86.1004]],

        ...,

        [[  17.1588,  -12.8483,  -45.9230,  ...,  -64.5072,  -41.2217,
           -42.7692]],

        [[  42.2582,   12.8430,   -5.5173,  ...,  -32.5435,   -8.9524,
           -12.2990]],

        [[  14.0774,   13.8146,  -12.5445,  ...,  -42.1252,  -21.8521,
           -22.7207]]], grad_fn=<ViewBackward>)
-填写)
填写)
0.06021404266357422


tensor([[[-109.8201, -116.1962, -125.6548,  ..., -167.4258, -153.7664,
          -157.6572]],

        [[  13.5764,  -18.6196,  -54.7257,  ...,  -84.0688, -107.4880,
          -114.0674]],

        [[   3.3654,  -33.5149,  -55.0285,  ...,  -94.9807, -106.8778,
          -107.2650]],

        ...,

        [[  13.2308,  -12.6405,  -40.1944,  ...,  -36.5106,  -40.5032,
           -40.2071]],

        [[  26.7665,   -0.1728,  -25.5684,  ...,  -47.6201,  -32.7355,
           -33.5851]],

        [[  -4.8041,  -11.9273,  -27.4199,  ...,  -57.3642,  -45.2279,
           -35.8526]]], grad_fn=<ViewBackward>)
》需慎写，
》需慎写，
0.0930643081665039


tensor([[[-35.7245, -26.9747, -65.6642,  ..., -46.2056, -60.1800, -50.7413]],

        [[ 14.4334, -12.9421, -41.3689,  ..., -32.8059, -65.0285, -77.1728]],

        [[ 12.2088, -22.8837, -58.7234,  ..., -58.9125, -73.3596, -79.8427]],

        ...,

        [[ 46.8604,   1.2497, -51.2007,  ..., -51.3450, -56.8474, -45.2826]],

        [[ 47.9569,   7.3621, -29.3660,  ..., -31.9545, -35.2637, -27.9846]],

        [[ 12.3882,  -0.1790, -24.1745,  ..., -17.4266, -23.7811, -23.4974]]],
       grad_fn=<ViewBackward>)
记录
记录
0.18515419960021973


tensor([[[-102.9876,  -96.3874, -130.3423,  ..., -136.7029, -142.2737,
          -128.4530]],

        [[   4.0733,  -34.7601,  -55.9292,  ...,  -55.8425, -106.6513,
           -99.9547]],

        [[ -15.1111,  -56.3055,  -84.7859,  ...,  -97.0110, -104.7572,
          -105.4777]],

        ...,

        [[   3.7817,  -47.4354,  -82.4748,  ...,  -92.6935,  -99.4708,
           -71.9713]],

        [[  -5.2493,  -53.1208,  -89.7057,  ...,  -84.7800, -101.0136,
           -68.8680]],

        [[  -9.3215,  -18.8980,  -27.7610,  ...,  -30.9774,  -42.1915,
           -30.8433]]], grad_fn=<ViewBackward>)
-申请人无需|-申请人无需--申请人无需|-申请人无需
申请人无需|-申请人无需--申请人无需|-申请人无需
0.6181612014770508


tensor([[[ -79.9423,  -78.8081,  -94.1392,  ..., -121.7836, -117.6230,
          -115.2926]],

        [[  19.6822,  -12.9565,  -57.2848,  ...,  -70.1285, -102.0159,
          -100.7530]],

        [[  14.8626,  -25.4762,  -46.4940,  ...,  -65.2404,  -78.0865,
           -76.0651]],

        ...,

        [[   7.3059,  -36.2467,  -63.2813,  ...,  -61.4977,  -69.8848,
           -46.0626]],

        [[  50.7960,    9.7244,    3.1014,  ...,    4.4079,  -11.5750,
             8.4825]],

        [[   4.5759,   -9.9164,  -10.3525,  ...,   -1.7215,  -12.8404,
           -10.8460]]], grad_fn=<ViewBackward>)
|示范数学考试-雪
|示范数学考试-雪
0.09189915657043457


tensor([[[-6.1472e+01, -6.2830e+01, -9.4580e+01,  ..., -1.0886e+02,
          -8.8399e+01, -9.9193e+01]],

        [[ 8.7054e+00, -1.6854e+01, -3.3589e+01,  ..., -4.1608e+01,
          -5.7148e+01, -7.9393e+01]],

        [[ 5.6704e+00, -3.1906e+01, -5.1917e+01,  ..., -7.3532e+01,
          -6.5525e+01, -9.1632e+01]],

        ...,

        [[ 4.9805e+01,  3.8559e+01,  3.3936e+01,  ...,  6.0141e+01,
           3.4904e+01,  2.0783e+01]],

        [[ 5.7051e+01,  2.6195e+01,  2.0683e+01,  ...,  4.6756e+01,
           1.6203e+01,  1.7699e+01]],

        [[ 3.5522e+01,  3.4436e+00,  1.3668e-02,  ...,  2.3510e+01,
          -1.0849e+01, -1.3204e+01]]], grad_fn=<ViewBackward>)
-填写
填写
0.050778865814208984


tensor([[[-5.3192e+01, -5.3814e+01, -9.2505e+01,  ..., -1.0507e+02,
          -8.5751e+01, -8.7811e+01]],

        [[ 1.8136e+01, -8.5018e+00, -3.3705e+01,  ..., -4.1233e+01,
          -5.8151e+01, -7.3633e+01]],

        [[ 7.3416e-02, -3.9030e+01, -5.6968e+01,  ..., -7.8792e+01,
          -7.1510e+01, -9.3587e+01]],

        ...,

        [[ 2.5165e+01, -5.9395e+00, -4.2987e+01,  ..., -6.3287e+01,
          -5.3581e+01, -4.0840e+01]],

        [[ 6.5333e+01,  3.5617e+01,  2.1436e+01,  ..., -8.0693e-02,
           8.5412e+00,  1.2994e+01]],

        [[ 4.2382e+01,  3.8865e+01,  1.7483e+01,  ..., -2.2141e+00,
           1.2757e+00,  4.7800e+00]]], grad_fn=<ViewBackward>)
-填写-
填写-
0.07503962516784668


tensor([[[ -53.6516,  -50.9826,  -78.7551,  ...,  -84.0556,  -55.1278,
           -75.7040]],

        [[   2.4800,  -38.1449,  -82.3441,  ...,  -90.7716, -115.9118,
          -127.5141]],

        [[ -26.8206,  -74.5402, -129.6451,  ..., -137.7147, -152.4515,
          -152.2089]],

        ...,

        [[  17.2014,   -4.6549,  -33.4758,  ...,  -70.9316,  -47.6719,
           -50.5875]],

        [[  58.6687,   30.8387,   13.0135,  ...,  -26.5748,   -4.9053,
            -1.3370]],

        [[  17.5373,   17.4186,   -4.9702,  ...,  -39.5840,  -17.0517,
           -14.9400]]], grad_fn=<ViewBackward>)
缜写}
缜写}
0.05212664604187012


tensor([[[-42.5474, -37.4678, -44.8460,  ..., -67.8220, -41.2191, -44.7981]],

        [[ 32.4365,  -2.4445, -33.5413,  ..., -48.5488, -68.1601, -74.3485]],

        [[ 30.5086, -10.5230, -44.6468,  ..., -72.7294, -61.4426, -68.8230]],

        ...,

        [[ 21.7331,  -2.4397,  -9.8880,  ..., -19.9382, -26.3955, -25.7049]],

        [[ 31.4590,   8.5523, -13.3609,  ..., -35.8355, -18.0791, -27.2282]],

        [[ -6.3075, -36.2500, -62.6558,  ..., -88.9775, -74.3785, -66.9275]]],
       grad_fn=<ViewBackward>)
交通主管
交通主管
0.07902193069458008


tensor([[[ -51.5603,  -48.9495,  -86.5046,  ...,  -89.6376, -100.7042,
           -77.1763]],

        [[  42.2065,    8.7504,  -36.6755,  ...,  -40.7835,  -82.6599,
           -69.6413]],

        [[  22.6889,  -27.2174,  -58.1706,  ...,  -72.5578,  -95.1149,
           -82.9861]],

        ...,

        [[  39.6232,   16.8323,  -18.6898,  ...,  -37.5537,  -21.1571,
           -15.7514]],

        [[  33.3219,    7.7884,  -18.9912,  ...,  -48.3117,  -35.9150,
           -32.2264]],

        [[  19.4059,   24.9073,  -12.1932,  ...,  -40.7310,  -25.2865,
           -22.0084]]], grad_fn=<ViewBackward>)
-申该人无需填写)
申该人无需填写)
0.13014888763427734


tensor([[[-56.1062, -54.3450, -80.1202,  ..., -77.1367, -72.4243, -56.5407]],

        [[ 33.4140,  -1.2315, -28.3511,  ..., -26.2044, -73.5486, -69.8802]],

        [[ 28.3765,  -8.9180, -49.3219,  ..., -50.6040, -59.5274, -66.5193]],

        ...,

        [[ -0.7880, -25.9810, -60.7764,  ..., -86.4050, -69.8871, -64.2238]],

        [[ 36.8231,  10.3806,  -8.9428,  ..., -37.9140, -15.5039, -13.8418]],

        [[-18.3530, -44.1395, -66.3108,  ..., -89.5319, -72.4296, -63.6717]]],
       grad_fn=<ViewBackward>)
部门恋见
部门恋见
0.1020498275756836


tensor([[[ -83.6865,  -85.7595, -104.9371,  ..., -131.8806, -126.9528,
          -118.6532]],

        [[  16.8249,  -12.4253,  -51.1591,  ...,  -63.8555,  -88.6306,
           -89.4429]],

        [[  17.2971,  -23.3506,  -41.0277,  ...,  -64.4652,  -84.3877,
           -77.6471]],

        ...,

        [[  -8.9532,  -32.8772,  -58.3131,  ...,  -82.4159,  -75.4752,
           -63.9101]],

        [[  22.9813,   -5.9676,  -13.9647,  ...,  -44.7069,  -44.8696,
           -28.5003]],

        [[ -15.3190,  -19.8784,  -28.2981,  ...,  -53.6465,  -56.7884,
           -38.3898]]], grad_fn=<ViewBackward>)
|-申请人无需填/
|-申请人无需填/
0.15836524963378906


tensor([[[ -60.8916,  -68.2799, -100.9211,  ..., -125.8852,  -99.4940,
          -107.7386]],

        [[  27.1851,   -6.8301,  -43.7297,  ...,  -54.3165,  -76.9425,
           -84.0625]],

        [[  -5.0508,  -41.7090,  -64.2752,  ...,  -86.3947,  -81.1808,
           -98.0163]],

        ...,

        [[  62.6906,   36.4766,   21.5383,  ...,    1.8668,    5.5732,
            10.4787]],

        [[  35.1250,   10.6472,  -13.8359,  ...,  -32.1519,  -33.2061,
           -23.1267]],

        [[  27.4797,    1.5727,  -24.5258,  ...,  -39.6274,  -39.6020,
           -27.2302]]], grad_fn=<ViewBackward>)
-发放人-签字-
发放人-签字-
0.2361903190612793


tensor([[[ -72.3644,  -79.9914, -113.2038,  ..., -122.8076, -104.0171,
          -105.5173]],

        [[  24.5819,   -4.5922,  -36.5619,  ...,  -45.3594,  -70.5629,
           -72.3825]],

        [[  -1.1776,  -37.2471,  -58.7415,  ...,  -79.9562,  -74.4850,
           -87.2029]],

        ...,

        [[  30.4464,    8.3192,  -17.6373,  ...,  -45.0374,  -29.4774,
           -30.4553]],

        [[  36.3785,    8.5970,  -21.6386,  ...,  -55.3067,  -47.0815,
           -32.2589]],

        [[  47.1913,   48.1043,    9.2327,  ...,  -16.5868,   -9.3809,
            12.4364]]], grad_fn=<ViewBackward>)
-日期-申谛人无需填写)
日期-申谛人无需填写)
0.13685131072998047


tensor([[[ -58.4641,  -56.0228,  -70.2842,  ...,  -88.6643,  -83.3294,
           -89.5740]],

        [[  30.7767,   -0.4929,  -27.7667,  ...,  -46.8098,  -70.5383,
           -85.1506]],

        [[  -9.2841,  -38.1061,  -59.0249,  ...,  -84.0294,  -96.4253,
          -108.3847]],

        ...,

        [[  22.5289,   -4.0773,  -44.8742,  ...,  -39.4375,  -48.5721,
           -30.3604]],

        [[  40.2558,    9.9085,  -14.4920,  ...,  -25.6242,  -20.4953,
           -16.3431]],

        [[  10.6773,  -26.5024,  -42.6926,  ...,  -69.1253,  -58.7198,
           -52.4773]]], grad_fn=<ViewBackward>)
，从业茨格
，从业茨格
0.15052247047424316


tensor([[[-11.9065, -12.6328, -27.6373,  ...,  -6.2706, -18.2774, -38.3149]],

        [[ 55.9122,  17.7100, -15.6111,  ...,   6.0857, -42.3058, -42.0969]],

        [[  8.9587, -33.4051, -61.7436,  ..., -58.5932, -80.8934, -86.4964]],

        ...,

        [[ 34.2750,   6.9198, -37.3800,  ..., -43.9631, -41.8371, -23.0469]],

        [[ 12.8824, -19.1556, -50.2777,  ..., -64.6750, -66.5668, -49.5651]],

        [[  5.0481,   0.9351, -22.2006,  ..., -34.9287, -36.8503, -30.1120]]],
       grad_fn=<ViewBackward>)
写)
写)
0.0436098575592041


tensor([[[-57.1710, -50.3734, -79.5320,  ..., -71.9189, -70.6301, -52.3548]],

        [[ 19.9011,  -9.1590, -58.0656,  ..., -62.6552, -91.7163, -90.5337]],

        [[ 11.4246, -28.2580, -78.0246,  ..., -83.5103, -95.5587, -90.3778]],

        ...,

        [[ 12.7374, -18.7823, -46.1939,  ..., -52.4154, -50.8090, -47.0940]],

        [[ 16.9348,  -8.5877, -37.9542,  ..., -53.3455, -44.6777, -42.5798]],

        [[ -2.5693, -32.9439, -53.8327,  ..., -77.6186, -64.6825, -56.0777]]],
       grad_fn=<ViewBackward>)
证件发放
证件发放
0.10216593742370605


tensor([[[ -74.1755,  -80.3201, -113.9766,  ..., -139.8086, -110.6035,
          -117.3375]],

        [[  22.1757,  -11.3226,  -47.5805,  ...,  -55.5140,  -76.4071,
           -84.2736]],

        [[  -1.2097,  -39.3849,  -70.5120,  ...,  -93.4524,  -91.0730,
          -106.3598]],

        ...,

        [[   6.0025,  -28.8860,  -76.7431,  ...,  -51.5335,  -80.0856,
           -43.5023]],

        [[  18.5638,  -27.1030,  -50.6801,  ...,  -27.0887,  -61.7655,
           -25.6424]],

        [[ -15.1031,  -26.4151,  -41.8704,  ...,  -11.0556,  -44.9976,
           -17.1459]]], grad_fn=<ViewBackward>)
-20XX年XX月XX日
20XX年XX月XX日
0.14482784271240234


tensor([[[ -70.2252,  -77.8709, -113.8068,  ..., -136.4854, -109.8805,
          -115.4973]],

        [[  24.5325,   -4.6084,  -43.1445,  ...,  -52.7523,  -77.0888,
           -77.5939]],

        [[  -5.9178,  -39.5601,  -63.6975,  ...,  -85.9871,  -79.1011,
           -95.8045]],

        ...,

        [[  40.6868,    9.8557,   -7.2076,  ...,  -26.0840,  -27.8353,
           -21.0238]],

        [[  34.5918,    9.6820,  -16.0509,  ...,  -35.7756,  -33.2784,
           -23.8453]],

        [[  18.9983,  -10.5094,  -33.6063,  ...,  -52.4684,  -49.6010,
           -39.0123]]], grad_fn=<ViewBackward>)
-领取人-签字-
领取人-签字-
0.1246495246887207


tensor([[[ -73.4875,  -79.6939, -107.6508,  ..., -142.0589, -114.8632,
          -118.3809]],

        [[  20.4671,   -5.8997,  -30.5054,  ...,  -46.4590,  -70.6818,
           -76.4734]],

        [[   3.5435,  -33.1404,  -48.2938,  ...,  -71.9338,  -67.5346,
           -83.7682]],

        ...,

        [[   7.1695,  -11.7429,  -40.6605,  ...,  -70.2248,  -57.4332,
           -58.4177]],

        [[  27.7947,    7.3518,  -25.7073,  ...,  -49.2019,  -30.2158,
           -26.2862]],

        [[   8.1935,  -17.1896,  -45.5119,  ...,  -66.9537,  -54.2763,
           -41.4523]]], grad_fn=<ViewBackward>)
-张XX
张XX
0.09119963645935059


tensor([[[ -77.8078,  -85.5856, -118.6600,  ..., -134.2041, -109.5466,
          -119.2269]],

        [[  27.6292,   -5.5037,  -44.5437,  ...,  -52.6968,  -72.8560,
           -79.8705]],

        [[  -1.1975,  -35.9487,  -61.9849,  ...,  -80.7127,  -76.8950,
           -88.1830]],

        ...,

        [[   0.3230,  -20.5405,  -54.3984,  ...,  -85.6522,  -69.1386,
           -64.3620]],

        [[  33.2992,    5.0453,  -12.2915,  ...,  -40.9205,  -22.3954,
           -22.5913]],

        [[ -36.7773,  -62.6562,  -79.1423,  ..., -103.6492,  -90.5855,
           -88.7842]]], grad_fn=<ViewBackward>)
-日期
日期
0.2047743797302246
